### ISSUE TITLE
request: make switchable

### ISSUE THREAD

**Issue by hvbhome** [custom-components/sensor.authenticated#2]
Please consider making this sensor switchable. Since it might weigh in on the system resources (since running the CC, processor usage hardly ever goes below 28%) it would really be nice if we could switch it on/off on demand

(in stead of taking out the CC, which is the only way of doing that now)

cheers,
Marius

**Comment by ludeeus** [comment]
The main purpose for this is to give you info about unknown connection to your instance, this should always be on, therefore I will not add an option to disable it.

But I will see if I can make it less heavy on the CPU, what hardware are you running this on?

**Comment by hvbhome** [comment]
Rpi 3B currently.

In the logs many connections to the internal IP address of my main computers are repeatedly shown. 
`MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)`
This might be something to exclude somehow? 
btw, would you know of a way/tool to determine the source of these internal ip addresses? I have no way now to see which device has which internal Ip address. say a AppleTv or so. Only see their Ip address in the router, of format 192.168.etc. but the 172. addresses are somewhat more obscure..

**Comment by ludeeus** [comment]
> This might be something to exclude somehow?
This is something I have no control over, this comes from the http component.

172.30 adreses are probably your docker containers (hassio addons)
I will look into doing lookups for local adresses

**Comment by ludeeus** [comment]
@hvbhome I have made some changes that should free up some resources now https://github.com/custom-components/sensor.authenticated/issues/3
https://github.com/custom-components/sensor.authenticated/commit/6120e1ebc58a6b13e760558ff7c0b713d77c0c18
