### ISSUE TITLE
Optional parameter for home-assistant.log location

### ISSUE THREAD

**Issue by thefrenchmatt** [custom-components/sensor.authenticated#22]
**Is your feature request related to a problem? Please describe.**
The log file can be saved to a non-standard location.
Example: "hass --log-file /var/log/homeassistant/home-assistant.log"

**Describe the solution you'd like**
Optional parameter in yaml config

**Describe alternatives you've considered**
Editing <CONFIG_DIR>/custom_components/sensor/authenticated.py
Updating value of LOGFILE to point to new location.

**Comment by ludeeus** [comment]
added in https://github.com/custom-components/sensor.authenticated/releases/tag/0.4.0
