### ISSUE TITLE
Switch back to ipapi or other provider

### ISSUE THREAD

**Issue by tjorim** [custom-components/sensor.authenticated#27]
**Is your feature request related to a problem? Please describe.**
The current API (ipvigilante) does not provide a lot of information about ip's compared to the old ipapi.co in my experience. My current IP only gives the country using the current provider.

**Describe the solution you'd like**
I would prefer switching back to the old one (reverting #13), or another provider entirely. Since there were a few updates regarding processing IP addresses multiple time, we might not hit the 1000 requests/day limit.

**Describe alternatives you've considered**
Using another provider for geolocating an IP address is also possible (e.g. apparently ipstack is pretty good as well). There are some that require registration to receive an API key but that doesn't need to be a problem in my opinion. There are a lot of default HA components that require API keys from users as well.

**Comment by ludeeus** [comment]
The next version will have this ;)
I have been testing it locally for some days now and it has not failed yet :)

**Comment by VirtualL** [comment]
Hi , I been looking for this change also , the info in the current API is very slim and Incomplete.
I also found this API very good and get a lot of information: http://extreme-ip-lookup.com/
And he gives me the most information.
This API in use at this custom component https://github.com/custom-components/sensor.geoip

**Comment by ludeeus** [comment]
@VirtualL the plan for the next version is to go back to using https://ipapi.co/json
Are there any thing in http://extreme-ip-lookup.com/json you are missing from https://ipapi.co/json?

**Comment by ludeeus** [comment]
@tjorim and @VirtualL 
This is now live https://github.com/custom-components/sensor.authenticated/releases/tag/0.3.0

**Comment by VirtualL** [comment]
I Think this API is better recognizes in general
This one is form my Work ,in the area of Jerusalem (not in Petah Tikva -its a more far from here)
![image](https://user-images.githubusercontent.com/10164935/44904468-12bd0d00-ad18-11e8-91f8-3db94e21b8db.png)

This one is from my Unraid server (the result are the same overall)
![image](https://user-images.githubusercontent.com/10164935/44904501-249eb000-ad18-11e8-9bcd-4248588b079d.png)

I don't know how much the difference in the US , Israel is a small Country and most of the ISP servers in the center of israel.

**Comment by ludeeus** [comment]
I have no preference here really.

@tjorim Does https://extreme-ip-lookup.com/ serve your needs?

**Comment by tjorim** [comment]
Hm, not sure, I'm getting mixed results.
Tested a few IPs of myself, school, a friend's home and their work.
I have the feeling that the city is more accurate on ipapi,
but half of the time city and region is just empty with extreme-ip-lookup.

**Comment by ludeeus** [comment]
@tjorim I had the same results as you when testing out the sites I have access to (scandinavia).
I'll look into supporting both

**Comment by ludeeus** [comment]
added in https://github.com/custom-components/sensor.authenticated/releases/tag/0.4.0

**Comment by VirtualL** [comment]
Thanks!
