### ISSUE TITLE
Seems to be not working with 0.91.0bx

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/sensor.authenticated#34]
**Version of the custom_component**

Newest Version 0.4.0
**Describe the bug**
Is not showing last authenticated IP address anymore.
**log**

```
THere are ZERO ENtries in the logs about this
Add your logs here.
```
![image](https://user-images.githubusercontent.com/36390762/55286041-08640e00-53e2-11e9-96f1-1def0f7de052.png)

**Comment by ludeeus** [comment]
Fixed here https://github.com/custom-components/sensor.authenticated/commit/eb27b24097ca22370727144c6daac118ad8aa6de
